from __future__ import annotations

AGENT_EXECUTION_ERROR = "AGENT_EXECUTION_ERROR"
AGENT_THREAD_ERROR = "AGENT_THREAD_ERROR"
CALCULATION_ERROR = "CALCULATION_ERROR"
CONFIG_ERROR = "CONFIG_ERROR"
EXCEL_TOOL_ERROR = "EXCEL_TOOL_ERROR"
EXCEL_TOOL_DEPENDENCY_ERROR = "EXCEL_TOOL_DEPENDENCY_ERROR"
EXCEL_TOOL_FILE_NOT_FOUND = "EXCEL_TOOL_FILE_NOT_FOUND"
EXCEL_TOOL_SHEET_EXISTS = "EXCEL_TOOL_SHEET_EXISTS"
EXCEL_TOOL_SHEET_NOT_FOUND = "EXCEL_TOOL_SHEET_NOT_FOUND"
FILE_TOOL_ERROR = "FILE_TOOL_ERROR"
LLM_ALL_PROVIDERS_FAILED = "LLM_ALL_PROVIDERS_FAILED"
LLM_RESPONSE_TRUNCATED = "LLM_RESPONSE_TRUNCATED"
LLM_CONFIG_ERROR = "LLM_CONFIG_ERROR"
LLM_HTTP_ERROR = "LLM_HTTP_ERROR"
LLM_NETWORK_ERROR = "LLM_NETWORK_ERROR"
LLM_PROVIDER_NOT_FOUND = "LLM_PROVIDER_NOT_FOUND"
LLM_RESPONSE_ERROR = "LLM_RESPONSE_ERROR"
LLM_RESPONSE_PARSE_ERROR = "LLM_RESPONSE_PARSE_ERROR"
LLM_TIMEOUT = "LLM_TIMEOUT"
SHELL_COMMAND_FAILED = "SHELL_COMMAND_FAILED"
SHELL_EXECUTION_ERROR = "SHELL_EXECUTION_ERROR"
SHELL_TIMEOUT = "SHELL_TIMEOUT"
SQL_QUERY_TOOL_ERROR = "SQL_QUERY_TOOL_ERROR"
SQL_SCHEMA_TOOL_ERROR = "SQL_SCHEMA_TOOL_ERROR"
STORAGE_CONFIG_ERROR = "STORAGE_CONFIG_ERROR"
STORAGE_DEPENDENCY_ERROR = "STORAGE_DEPENDENCY_ERROR"
STORAGE_QUERY_ERROR = "STORAGE_QUERY_ERROR"
STORAGE_RESOURCE_NOT_FOUND = "STORAGE_RESOURCE_NOT_FOUND"
STORAGE_RESOURCE_REQUIRED = "STORAGE_RESOURCE_REQUIRED"
TOOL_ARGUMENT_ERROR = "TOOL_ARGUMENT_ERROR"
TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
TOOL_TIMEOUT = "TOOL_TIMEOUT"
PYTHON_TOOL_ERROR = "PYTHON_TOOL_ERROR"
PYTHON_TOOL_FORBIDDEN_IMPORT = "PYTHON_TOOL_FORBIDDEN_IMPORT"
PYTHON_TOOL_TIMEOUT = "PYTHON_TOOL_TIMEOUT"
PYTHON_TOOL_RESOURCE_LIMIT = "PYTHON_TOOL_RESOURCE_LIMIT"
VECTOR_SCHEMA_TOOL_ERROR = "VECTOR_SCHEMA_TOOL_ERROR"
VECTOR_SEARCH_TOOL_ERROR = "VECTOR_SEARCH_TOOL_ERROR"


class AgentError(Exception):
    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.message = message
        super().__init__(str(self))

    def __str__(self) -> str:
        return f"[{self.code}] {self.message}"


def build_error(code: str, message: str) -> AgentError:
    return AgentError(code=code, message=message)


class ConfigError(AgentError):
    def __init__(self, message: str) -> None:
        super().__init__(code=CONFIG_ERROR, message=message)
